/Users/nsmith/Desktop/greek2021/Kanones.jl/model/greek.a: /Users/nsmith/Desktop/greek2021/Kanones.jl/model/symbols.fst /Users/nsmith/Desktop/greek2021/Kanones.jl/model/acceptor.a /Users/nsmith/Desktop/greek2021/Kanones.jl/model/inflection.a
%.a: %.fst
	/usr/local/bin/fst-compiler-utf8 $< $@
