project:
  type: website
jupyter: julia-1.10  
execute:
  freeze: auto
date: last-modified  
margin-header: "⚠️ *These are incomplete preliminary notes from a pre-release draft.*"
format:
  html: default


website:
 
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Tutorials"
        file: tutorials/index.qmd          
      - text: "Concepts"
        file: concepts/index.qmd   
      - text: "Guides"
        file: guides/index.qmd           
      - text: "Reference"
        file: reference/index.qmd  
    right:   
      - icon: github
        href: https://github.com/neelsmith/Kanones.jl
        aria-label: GitHub

  sidebar:
    - title: "Tutorials"
      contents: 
        - tutorials/index.qmd
        - tutorials/parser.qmd
        - tutorials/prebuilt.qmd
        - tutorials/prebuilt-adds.qmd   
    - title: "Guides"
      contents:
        - guides/index.qmd
        - text: "---"
        - guides/dataset-guide.qmd
        - guides/dataset-strategies.qmd
        - guides/dataset-profile.qmd        
        - text: "---"
        - guides/nounstems-guide.qmd
        - guides/adjectivestems-guide.qmd
        - guides/verbstems-guide.qmd   
        - guides/irregularstems-guide.qmd   
        - guides/inflectional-rules.qmd  
        - text: "---"   
        - guides/registry.qmd  
        - guides/lexicon.qmd
        - text: "---"   
        - guides/datainjulia-forms.qmd  
        - guides/utilities.qmd
    - title: "Reference"
      contents: 
        - reference/index.qmd
        - reference/properties.qmd
        - reference/forms.qmd
        - reference/infltypes.qmd
        - reference/generating.qmd
    - title: "Concepts"
      contents: 
        - concepts/index.qmd
        - concepts/motivation.qmd
        - concepts/bg.qmd
        - concepts/orthography.qmd
        - concepts/analyses.qmd

        

    - title: "Home"
      contents:
        - index.qmd               
 

           