---
title: "Kanones.jl"
jupyter: julia-1.10
---

> ☛ *Build customized morphological parsers for ancient Greek*


::: {.callout-caution} 
## Caution!


*This web site is a dump of preliminary notes from a pre-release draft of documentation for `Kanones.jl`. Please check back later in summer 2024 for more useful documentation.*

*Pages flagged with 🤷‍♂️ in the title are not yet in a usable form.*

:::


## Kanónes



`Kanones.jl` is a Julia package for building Greek morphological parsers. Its features include:

- data managed in delimited-text tables that you can modify or add to with any text editor
- rigorously defined orthographies.  Example parsers implement a standard orthography of printed editions of literary Greek, and an orthography for epigraphic Greek in the alphabet used by Athens before 403 BCE.
- implemented entirely in the Julia language (no other technical prerequisites): 
    - platform independent
    - fast:  a parser built with Kanones on consumer-grade hardware can typically parse a token in 1-9 milliseconds.
    - code library can be used from command line, in scripts, in web apps, directly in an editor like Visual Studio Code


## Using Kanones.jl


- [Get started](tutorials/index.qmd)!
- [Recipes](guides/index.qmd) for working with `Kanones.jl`


## Learning about the Kanónes system

- [Understanding Kanónes](concepts/index.qmd)
- [Reference](reference/index.qmd)