/Users/nsmith/Desktop/morphology/Kanones.jl/fst-scratch/augfull/greek.a: /Users/nsmith/Desktop/morphology/Kanones.jl/fst-scratch/augfull/symbols.fst /Users/nsmith/Desktop/morphology/Kanones.jl/fst-scratch/augfull/acceptor.a /Users/nsmith/Desktop/morphology/Kanones.jl/fst-scratch/augfull/inflection.a
%.a: %.fst
	/usr/local/bin/fst-compiler-utf8 $< $@
