---
title: "Using morphological objects in Julia"
editor:
    render-on-save: true
---


## Overview

Morphological forms are identified with morphological properties: for example, nouns and adjectives are identified with gender, case and number properties; infinitive verbs are identified with tense and voice.

Kanónes defines properties for person, number, tense, mood, voice, gender, case, degree and uninflected part of speech. Each property is a subtype of the abstract `GreekMorphologicalProperty` that has a name starting with `GMP` (for Greek morphological property), followed by a label. The tense property is implemented with the `GMPTense` type.

Instances of these types may be constructed from numeric codes, or from a string value returned by its `label` function.  Kanónes provides constructor functions with names identical to the type but with initial lowercase `gmp`.



```{julia}
#| warning: false
using Kanones
gmpTense(3)
```


```{julia}
tense = gmpTense(3)
```


All properties work with the `label` and `code` functions.`

```{julia}
label(tense)
```

```{julia}
code(tense)
```

## Summary of property values

Person: three values labelled `first`, `second`, `third`.


```{julia}
gmpPerson(3) == gmpPerson("third")
```

Number: three values labelled `singular`, `dual`, `plural`.

```{julia}
gmpNumber(3) == gmpNumber("plural")
```

Tense: six values labelled `present`, `imperfect`, `aorist`, `perfect`, `pluperfect` and `future`.

```{julia}
gmpTense(3) == gmpTense("aorist")
```


Mood: four values labelled `indicative`, `subjunctive`, `optative`, `imperative`.


```{julia}
gmpMood(1) == gmpMood("indicative")
```


Voice: three values labelled `active`, `middle`, `passive`.

```{julia}
gmpVoice(2) == gmpVoice("middle")
```


Gender: three values labelled `masculine`, `feminine`, `neuter`.


```{julia}
gmpGender(2) == gmpGender("feminine")
```



Case: five values labelled `nominative`, `genitive`, `dative`, `accusative`, `vocative`.

```{julia}
gmpCase(2) == gmpCase("genitive")
```


Degree: three values labelled `positive`, `comparative`, `superlative`.

```{julia}
gmpDegree(2) == gmpDegree("comparative")
```

Uninflected part of speech: six values labelled `conjunction`,
    `preposition`, `particle`, `adverb`, `numeral`, `interjection`
   

```{julia}
gmpUninflectedType(2) == gmpUninflectedType("preposition")
```
