---
title: "Build a parser and parse a Greek string"
---

```{julia}
#| echo: false
#| output: false

repo = pwd() |> dirname |> dirname
```

::: {.callout-tip}
## Follow along

To replicate all the steps in this tutorial:

- [install Julia](https://julialang.org/downloads/) if you haven't already done so
- download or clone the [Kanones.jl repository](https://github.com/neelsmith/Kanones.jl)
- start a Julia REPL
::: 

## Building a parser

You can build a parser from delimited-text files organized in directories following Kanónes' conventions. This example uses [the `literarygreek-rules` data set](https://github.com/neelsmith/Kanones.jl/tree/main/datasets/literarygreek-rules) from the `datasets` directory of the Kanónes github repository.

If you have a variable named `repo` with the root directory of the Kanónes repository, then the `literarygreek-rules` directory will be:

```{julia}
srcdir = joinpath(repo, "datasets", "literarygreek-rules") 
```

You can create a `Kanones.FilesDataSet` from a list of one or more directories with Kanónes data.

```{julia}
using Kanones
kds = dataset([srcdir])
```

You can then build a parser from a data set.

```{julia}
#| warnings: false
p = stringParser(kds)
```



### Interactive parsing

Use the `parsetoken` function to parse a string with a parser. 


```{julia}
s = "ἀνθρώπῳ"
parses = parsetoken(s, p)
```

The result is a Vector of analyses.

Extract a `GreekMorphologicalForm` from each analysis, and apply the `label` function to each:

```{julia}
parses .|> greekForm .|> label
```

Extract URNs for the lexeme from each analysis with the `lexemeurn` function from the `CitableParserBuilder` package:

```{julia}
using CitableParserBuilder
lexemelist = parses .|> lexemeurn
```

After downloading LSJ labels for lexemes in the `lsj` collection, label lexemes with LSJ labels included.

```{julia}
lsj = lemmatadict()
```

```{julia}
lemmalabel.(lexemelist, dict = lsj)
```